import fs from 'node:fs';
const FILE = new URL('./index.html', import.meta.url);
let s = fs.readFileSync(FILE, 'utf8');
const CRLF = s.includes('\r\n'); if (CRLF) s = s.split('\r\n').join('\n');
const sub = (from, to, n = 1) => { const c = s.split(from).length - 1;
    if (c !== n) throw new Error(`Ancre (${c}/${n}) : ${from.slice(0,110)}`); s = s.split(from).join(to); };

sub(`                    const CURRENT_VERSION = "37.8 Une-Seule-Verite-CashFlow";`,
    `                    const CURRENT_VERSION = "37.9 Reparation-Et-Verdict";`);

const E = [
`        { version: "37.9 Reparation-Et-Verdict", date: "2026-09-25", changes: [`,
`            "LA CAUSE DU COMPTE COURANT À −600 000 DH. Jusqu'à la v37.8, « Appliquer ce scénario » exécutait littéralement : courantCompte.solde = solde − montant, où « montant » était le PRIX COMPLET du bien. Un achat simulé à 600 000 DH débitait donc 600 000 DH de vos VRAIES données, et créait un actif payé comptant (apport = prix, crédit = 0). Ce n'était pas une projection fausse : c'était une écriture dans le fichier. De là le patrimoine liquide à −554 300 DH et l'atterrissage négatif fin 2026, sans qu'aucune dépense réelle n'ait eu lieu.",`,
`            "RÉPARATION INTÉGRÉE — le simulateur retrouve ces applications et les défait, exactement à l'envers : l'actif est retiré, le montant est recrédité sur le compte courant. La signature est l'identifiant : « Appliquer ce scénario » est le seul à produire ma_<horodatage>_<suffixe> ; un actif saisi à la main s'appelle ma_<horodatage> sans suffixe. Vérifié : un actif saisi à la main posé à côté n'est pas confondu. La date d'application est affichée (elle est dans l'identifiant), et rien n'est fait sans confirmation. Si l'actif a déjà été supprimé mais que le débit est resté, un second bloc permet de recréditer le montant à la main.",`,
`            "UNDO NE FAISAIT RIEN — TROIS CAUSES, TOUTES MESURÉES. (1) Chaque modification était enregistrée DEUX fois : l'appel explicite à handleDataChange(), puis le watcher profond qui le rappelle. L'historique n'était qu'une suite de doublons, donc reculer d'un cran retombait sur l'état courant : Undo « marchait » sans rien changer. Mesuré : trois modifications successives faisaient passer le compteur de 1 à 3 à 5, et quatre Undo ne bougeaient rien. (2) Le verrou anti-réenregistrement était relâché sur la ligne suivant la restauration, alors que les watchers de Vue ne se déclenchent qu'au flush suivant : l'état restauré était aussitôt réenregistré, ce qui tuait Redo. (3) L'historique ne couvrait que 2 champs sur 8 — ni les objectifs, ni les actifs, ni les soldes initiaux. C'est pour cela que le débit du scénario était irrattrapable.",`,
`            "UNDO RÉPARÉ ET VÉRIFIÉ — instantanés dédoublonnés, verrou relâché après le flush, et TOUT le document couvert (mêmes champs que l'export, moins les identifiants Google Drive). Profondeur portée de 10 à 30 pas, qui sont maintenant 30 actions réelles et non 15. Un point zéro est posé au chargement : la toute première modification est désormais annulable, ce qui n'était pas le cas. Mesuré après correction : 3 modifications → 3 Undo → retour exact à l'état chargé, Redo fonctionnel, un actif créé annulé puis rétabli.",`,
`            "APPLIQUER UN SCÉNARIO, DÉSORMAIS — un récapitulatif chiffré ligne par ligne avant validation (ce qui sort du cash, ce qui entre à la dette, ce qui entre à l'actif), un instantané pris AVANT l'écriture, et un seul Undo pour tout défaire. La bannière promettait « réversible via Undo » alors que l'historique ignorait les actifs : la promesse est maintenant tenue.",`,
`            "LE VERDICT, AVANT LE TABLEAU — « en quoi cette simulation me permet d'acheter ? » Le simulateur répond maintenant en haut : point bas de trésorerie sur l'horizon et son année, marge réellement mobilisable (apport + frais compris), et par opération le cash à sortir, la mensualité, le loyer net, le cash-flow mensuel et la part du loyer absorbée par la mensualité.",`,
`            "JUSQU'À QUEL PRIX — ET LA QUESTION A-T-ELLE UN SENS ? Première version de ce calcul : une dichotomie supposant le point bas décroissant avec le prix. Mesuré, c'était faux : sur un scénario où la trésorerie touche son creux en 2026 et l'achat a lieu en 2027, le point bas vaut 900 000 DH pour TOUS les prix, de 1 % à 500 % — et la dichotomie renvoyait quand même « prix maximum finançable : 3 730 000 DH ». Un chiffre né du bruit. Remplacé par un balayage : on mesure, on n'affine que là où le balayage a établi la frontière, et quand le prix ne déplace pas le point bas on le DIT au lieu d'inventer un plafond.",`,
`            "ET LE CHIFFRE EST NOMMÉ POUR CE QU'IL EST — la zone tenable n'est pas toujours d'un seul tenant : au-delà du point de rupture, un bien plus cher se loue plus cher et finit par porter sa charge. Ce n'est donc pas un « prix maximum » mais « le scénario tient jusqu'à X DH », avec l'année de rupture et, le cas échéant, le prix à partir duquel il redevient tenable.",`,
`            "D'OÙ VIENT LE CHIFFRE — décomposition de l'année du point bas : chaque poste qui sort du cash, du plus lourd au plus léger, avec son montant mensuel, son coût sur les mois restants, sa nature (charge fixe, mensualité de crédit, charge variable, dépense ponctuelle) et un bouton qui emmène le modifier au bon endroit.",`,
`            "VOTRE HYPOTHÈSE ÉTAIT FAUSSE, ET C'EST MESURÉ — un versement d'épargne ne rend JAMAIS l'atterrissage négatif. Vérifié en retirant un versement de 2 000 DH/mois vers une poche virtuelle puis un de 3 000 DH/mois vers un compte marqué « hors liquidité » : l'atterrissage ne bouge pas d'un dirham. Retirer une charge fixe de 5 000 DH/mois le remonte de 20 000 DH (quatre mois restants). Un versement déplace l'argent d'une poche à l'autre, et le total les compte toutes. C'est écrit dans le panneau, pour ne plus chercher du mauvais côté.",`,
`            "AU PASSAGE, MA PROPRE SONDE M'A MENTI — en testant la frontière de prix, je mutais l'objet brut poussé dans le tableau réactif. Vue lit bien la nouvelle valeur mais ne notifie personne : le computed gardait son cache et j'ai cru un instant que le calcul de l'application était faux. Il était juste — le point bas décroît linéairement et croise zéro à 2 162 000 DH, exactement le chiffre annoncé. C'est le test qui a été corrigé."`,
`        ] },`].join('\n');

sub(`                    const CHANGELOG = [\n`, `                    const CHANGELOG = [\n${E}\n`);
if (CRLF) s = s.split('\n').join('\r\n');
fs.writeFileSync(FILE, s, 'utf8');
console.log('✅ version 37.9 + changelog');
